name: Naill-master DEmo

on:
  workflow_dispatch:

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  PORT: ${{ secrets.PORT }}

jobs:
  Naill-Run:
    runs-on: ubuntu-latest
    steps:
      #   - run: sudo apt update
      #   - run: sudo apt upgrade -y
      - run: echo "hello"
      - run: echo ${{ env.PORT }}
